print("Country _____, take me home")
print("To the place I _____")
print("West _____, mountain mama")
print("Take me home, _____ roads")
pn = input("Enter a plural noun: ")
pt = input("Enter a present-tense verb: ")
l = input("Enter a location: ")
a = input("Enter a adjective: ")
print("Country",pn + ',',"take me home")
print("To the place I",pt)
print("West",l + ',',"mountain mama")
print("Take me home,",a,"roads")
